project/cliente/urls.py
from django.urls import path

from cliente.views import cliente_list, index

app_name = "cliente"

urlpatterns = [
    path("", index, name="index"),
    path("cliente/list", cliente_list, name="cliente_list"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("core/", include("core.urls")),
     path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
]

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from core.views import index, sobre_nosotros

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("sobre-nosotros/", sobre_nosotros, name= "nosotros"),
]

project/cliente/models.py
from django.db import models


class Pais(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self) -> str:
        return self.nombre

    class Meta:
        verbose_name = "país"
        verbose_name_plural = "países"


class Cliente(models.Model):
    nombre = models.CharField(max_length=150)
    apellido = models.CharField(max_length=150)
    nacimiento = models.DateField(null=False, blank=False)
    pais_origen_id = models.ForeignKey(
        Pais, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="país de origen"
    )

    def __str__(self) -> str:
        return f"{self.apellido}, {self.nombre}"

    class Meta:
        verbose_name = "cliente"
        verbose_name_plural = "clientes"

project/cliente/views.py
from django.shortcuts import render

from cliente.models import Cliente


def index(request):
    return render(request, "cliente/index.html")


def cliente_list(request):
    consulta = Cliente.objects.all()
    contexto = {"clientes": consulta}
    return render(request, "cliente/cliente_list.html", contexto)

project/cliente/templates/cliente/cliente_list.html
{% extends 'core/base.html' %}

{% block title %}
    Cliente | Cliente: listado
{% endblock title %}

{% block body_title %}
    Cliente: Listado de clientes
{% endblock body_title %}

{% block content %}
    {% for cliente in clientes %}
        <ul>
            <li><h3>{{ cliente }}</h3></li>
            <p>Nacimiento: {{ cliente.nacimiento }}</p>
            {% if cliente.pais_origen_id %}
                <p>País de origen: {{ cliente.pais_origen_id }}</p>
            {% else %}
                <p>País de origen: "No hay registro"</p>
            {% endif %}
        </ul>
    {% endfor %}
{% endblock content %}

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block title %}
    Cliente
{% endblock title %}

{% block body_title %}
    App Cliente
{% endblock body_title %}

{% block content %}
    <div>
        <a href="{% url 'cliente:cliente_list' %}">Lista de clientes</a>
    </div>
{% endblock content %}