project/cliente/urls.py
from django.urls import path

from cliente.views import cliente_list, index

app_name = "cliente"

urlpatterns = [
    path("", index, name="index"),
    path("cliente/list", cliente_list, name="cliente_list"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("core/", include("core.urls")),
     path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
]

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from core.views import index, sobre_nosotros

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("sobre-nosotros/", sobre_nosotros, name= "nosotros"),
]

project/producto/urls.py
from django.urls import path

from producto.views import (
    ProductoCategoriaCreate,
    ProductoCategoriaDelete,
    ProductoCategoriaDetail,
    ProductoCategoriaList,
    ProductoCategoriaUpdate,
    ProductoCreate,
    ProductoDelete,
    ProductoDetail,
    ProductoList,
    ProductoUpdate,
    index,
)

app_name = "producto"

# VISTAS BASADAS EN FUNCIONES
urlpatterns = [
    path("", index, name="index"),
  
]

# VISTAS BASADAS EN CLASES
urlpatterns += [
    path("productocategoria/list", ProductoCategoriaList.as_view(), name="productocategoria_list"),
    path("productocategoria/create", ProductoCategoriaCreate.as_view(), name="productocategoria_create"),
    path("productocategoria/detail/<int:pk>", ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
    path("productocategoria/update/<int:pk>", ProductoCategoriaUpdate.as_view(), name="productocategoria_update"),
    path("productocategoria/delete/<int:pk>", ProductoCategoriaDelete.as_view(), name="productocategoria_delete"),
]

urlpatterns += [
    path("producto/list", ProductoList.as_view(), name="producto_list"),
    path("producto/create", ProductoCreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", ProductoDetail.as_view(), name="producto_detail"),
    path("producto/update/<int:pk>", ProductoUpdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>", ProductoDelete.as_view(), name="producto_delete"),
]

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

project/core/views.py
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from .forms import CustomAuthenticationForm, CustomUserCreationForm


def index(request):
    return render(request, "core/index.html")


def sobre_nosotros(request):
    return render(request, "core/sobre-nosotros.html")

project/core/templates/core/components/footer.html
<!-- Footer-->
<footer class="pie row">
    <!-- Contacto -->
    <div class="contacto col-sm-12 col-md-6 col-l-4 col-xl-4">
      <a href="href="https://wa.me/5493544610615" target="_blank" class="btn btn-primary">Whatsapp</a>
         <h5 class="display-3">✉️ Mail: info@recanton.com.ar</h5>
    </div>
    <!-- Consulta -->
    <div class="consulta col-sm-12 col-md-10 col-l-4 col-xl-4">
        <form action="">
          <h3 class="display-4">¡Envíanos tu consulta!</h3>
            <div class="mb-3">
                <label for="FormControlInput1" class="form-label">Nombre y Apellido</label>
                <input type="text" class="form-control" id="FormControlInput1" placeholder="Nombre Apellido">
            </div>
            <div class="mb-3">
                <label for="FormControlInput2" class="form-label">Teléfono</label>
                <input type="number" class="form-control" id="FormControlInput2" placeholder="0000-000000">
              </div>
            <div class="mb-3">
                <label for="FormControlInput3" class="form-label">Mail</label>
                <input type="email" class="form-control" id="FormControlInput3" placeholder="nombre@gmail.com">
              </div>
              <div class="mb-3">
                <label for="FormControlTextarea4" class="form-label">Escribe aquí tu consulta</label>
                <textarea class="form-control" id="FormControlTextarea4" rows="3"></textarea>
              </div>
        </form>
    </div>
    <!-- Ubicación -->
    <div class="ubicacion col-sm-12 col-md-12 col-l-4 col-xl-4">
      <iframe class="mapa" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1552.2802010066612!2d-65.18001858032727!3d-31.946058238043445!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x942cd567eb01fbbd%3A0x5f66a5595d18a286!2sAnton%20Rectificaciones%20SRL!5e0!3m2!1ses!2sar!4v1685313690636!5m2!1ses!2sar" title="mapa"></iframe>
      <h5 class="display-3">Avenida Belgrano 777, Villa Dolores, Córdoba - Argentina</h5>  
    </div>    
</footer>

project/core/templates/core/components/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Rectificaciones Anton</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active"
                   aria-current="page"
                   href="{% url 'core:index' %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="sobre-nosotros.html">Sobre Nosotros</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="venta-de-repuestos.html">Venta de Repuestos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="presupuesto.html">Presupuestos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="inicio-sesion.html">Inicio Sesión</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">La Caja de Pandora</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active"
                       aria-current="page"
                       href="{% url 'core:index' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% {% url 'core:nosotros' %}}">Nosotros</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'producto:index' %}">Producto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cliente:index' %}">Cliente</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-bg-info">{{ user.username }}</a>
                    </li>
            </ul>
        </div>
    </div>
</nav>

project/core/templates/core/components/titulo1.html
<div class="container px-4 py-lg-4">
    <div class="row align-items-center my-5">
        <h1 class="display-4 text-center mb-4 bg-info text-white ">
           {{ titulo }}
        </h1>
    </div>
</div>