project/config/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("core/", include("core.urls")),
     path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
]

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from core.views import index, sobre_nosotros

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("sobre-nosotros/", sobre_nosotros, name= "nosotros"),
]

project/producto/urls.py
from django.urls import path

from producto.views import (
    ProductoCategoriaCreate,
    ProductoCategoriaDelete,
    ProductoCategoriaDetail,
    ProductoCategoriaList,
    ProductoCategoriaUpdate,
    ProductoCreate,
    ProductoDelete,
    ProductoDetail,
    ProductoList,
    ProductoUpdate,
    index,
)

app_name = "producto"

# VISTAS BASADAS EN FUNCIONES
urlpatterns = [
    path("", index, name="index"),
  
]

# VISTAS BASADAS EN CLASES
urlpatterns += [
    path("productocategoria/list", ProductoCategoriaList.as_view(), name="productocategoria_list"),
    path("productocategoria/create", ProductoCategoriaCreate.as_view(), name="productocategoria_create"),
    path("productocategoria/detail/<int:pk>", ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
    path("productocategoria/update/<int:pk>", ProductoCategoriaUpdate.as_view(), name="productocategoria_update"),
    path("productocategoria/delete/<int:pk>", ProductoCategoriaDelete.as_view(), name="productocategoria_delete"),
]

urlpatterns += [
    path("producto/list", ProductoList.as_view(), name="producto_list"),
    path("producto/create", ProductoCreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", ProductoDetail.as_view(), name="producto_detail"),
    path("producto/update/<int:pk>", ProductoUpdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>", ProductoDelete.as_view(), name="producto_delete"),
]

project/producto/models.py
from django.db import models
from django.utils import timezone


class ProductoCategoria(models.Model):
    """Categorías de productos"""

    nombre = models.CharField(max_length=200, unique=True)
    descripcion = models.TextField(
        null=True,
        blank=True,
        verbose_name="descripción",
    )

    def __str__(self) -> str:
        """Retorna una instancia del modelo en forma de cadena de texto"""
        return self.nombre

    class Meta:
        verbose_name = "categoría de producto"
        verbose_name_plural = "categorías de producto"


class Producto(models.Model):
    categoria_id = models.ForeignKey(ProductoCategoria, null=True, blank=True, on_delete=models.SET_NULL)
    nombre = models.CharField(max_length=200)
    unidad_de_medida = models.CharField(max_length=200)
    cantidad = models.FloatField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.TextField(null=True, blank=True, verbose_name="descripción")
    fecha_actualizacion = models.DateField(null=True, blank=True, editable=False, default=timezone.now)

    def __str__(self) -> str:
        return f"{self.nombre} ({self.unidad_de_medida}) ${self.precio:.2f}"

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

project/producto/forms.py
from django import forms

from . import models


class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = ["nombre", "descripcion"]


class ProductoForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = "__all__"
        widgets = {
            "categoria_id": forms.Select(attrs={"class": "form-control"}),
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
            "unidad_de_medidda": forms.TextInput(attrs={"class": "form-control"}),
            "precio": forms.TextInput(attrs={"class": "form-control"}),
            "fecha_actualizacion": forms.TextInput(attrs={"class": "form-control"}),
        }

project/producto/views.py
from typing import Any

from django.db.models import Q
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from producto.forms import ProductoCategoriaForm, ProductoForm
from producto.models import Producto, ProductoCategoria


def index(request):
    return render(request, "producto/index.html")


# PRODUCTO CATEGORIA
# LISTA
class ProductoCategoriaList(ListView):
    model = ProductoCategoria
    # context_object_name = "productocategoria"
    # template_name = "producto/list.html"

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("busqueda")
        if busqueda:
            queryset = ProductoCategoria.objects.filter(
                Q(nombre__icontains=busqueda) | Q(descripcion__icontains=busqueda)
            )
        return queryset


# CREAR
class ProductoCategoriaCreate(CreateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")


# DETALLE
class ProductoCategoriaDetail(DetailView):
    model = ProductoCategoria


# ACTUALIZAR
class ProductoCategoriaUpdate(UpdateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")


# ELIMINAR
class ProductoCategoriaDelete(DeleteView):
    model = ProductoCategoria
    success_url = reverse_lazy("producto:productocategoria_list")


# PRODUCTO
class ProductoList(ListView):
    model = Producto

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("busqueda")
        if busqueda:
            queryset = Producto.objects.filter(nombre__icontains=busqueda)
        return queryset


class ProductoCreate(CreateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy("producto:producto_list")


class ProductoDetail(DetailView):
    model = Producto


class ProductoUpdate(UpdateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy("producto:producto_list")


class ProductoDelete(DeleteView):
    model = Producto
    success_url = reverse_lazy("producto:producto_list")

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}

{% block title %}
    Producto
{% endblock title %}

{% block body_title %}
    App Producto
{% endblock body_title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">Categorías de Productos</h5>
                    <a href="{% url 'producto:productocategoria_list' %}" class="btn btn-primary">Lista de categorías de productos</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">Crear Categoría de Productos</h5>
                    <a href="{% url 'producto:productocategoria_create' %}" class="btn btn-primary">Crear categoría de productos</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">Productos</h5>
                    <a href="{% url 'producto:producto_list' %}" class="btn btn-primary">Lista de productos</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">Crear Productos</h5>
                    <a href="{% url 'producto:producto_create' %}" class="btn btn-primary">Crear de productos</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

project/producto/templates/producto/producto_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
    Producto | Productos
{% endblock title %}

{% block body_title %}
    Producto - Productos: Eliminar
{% endblock body_title %}

{% block content %}
    <p class="fs-5  fst-italic ">¿Confirma eliminar "{{ object.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar</button>
    </form>
    <a href="{% url 'producto:index' %}">Volver al inicio de Producto</a>
{% endblock content %}

project/producto/templates/producto/producto_detail.html
{% extends 'core/base.html' %}

{% block title %}
    Producto | Productos
{% endblock title %}

{% block body_title %}
    Producto - Productos: Vista en Detalle
{% endblock body_title %}

{% block content %}
    <ul>
        <li>Categoría: {{ object.categoria_id }}</li>
        <li>Nombre: {{ object.nombre }}</li>
        <li>Precio: {{ object.precio }}</li>
        <li>Cantidad: {{ object.cantidad }}</li>
        <li>Actualización: {{ object.fecha_actualizacion }}</li>
    </ul>
    <div>
        <a href="{% url 'producto:producto_list' %}">Volver</a>
    </div>
{% endblock content %}

project/producto/templates/producto/producto_form.html
{% extends 'core/base.html' %}

{% block title %}
    Producto | Productos
{% endblock title %}

{% block body_title %}
    {% if form.instance.pk %}
        Producto - Productos: Edición
    {% else %}
        Producto - Productos: Creación
    {% endif %}
{% endblock body_title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Guardar</button>
    </form>
{% endblock content %}

project/producto/templates/producto/producto_list.html
{% extends 'core/base.html' %}

{% block title %}
    Producto | Producto: listado
{% endblock title %}

{% block body_title %}
    Producto - Producto: Listado
{% endblock body_title %}

{% block content %}
    <div class="container mt-5">
        <div class="row mb-3">
            <div class="col-lg-6">
                <form action="{% url 'producto:producto_list' %}"
                      method="get"
                      class="input-group">
                    <input type="text"
                           name="busqueda"
                           class="form-control"
                           placeholder="Buscar...">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">Buscar</button>
                    </div>
                </form>
            </div>
        </div>
        {% if object_list %}
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Precio</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.nombre }}</td>
                                <td>${{ object.precio }}</td>
                                <td>
                                    <a href="{% url 'producto:producto_detail' object.id %}"
                                       class="btn btn-info btn-sm">Detalle</a>
                                    <a href="{% url 'producto:producto_update' object.id %}"
                                       class="btn btn-warning btn-sm">Cambiar</a>
                                    <a href="{% url 'producto:producto_delete' object.id %}"
                                       class="btn btn-danger btn-sm">Borrar</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="fs-3">No hay registros</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}

project/producto/templates/producto/productocategoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
    Producto | Categoría de Productos
{% endblock title %}

{% block body_title %}
    Producto - Categorías de Productos: Eliminar
{% endblock body_title %}

{% block content %}
    <p class="fs-5  fst-italic ">¿Confirma eliminar "{{ object.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar</button>
    </form>
    <a href="{% url 'producto:index' %}">Volver al inicio de Producto</a>
{% endblock content %}

project/producto/templates/producto/productocategoria_detail.html
{% extends 'core/base.html' %}

{% block title %}
    Producto | Categorías de Productos
{% endblock title %}

{% block body_title %}
    Producto - Categorías de Productos: Vista en Detalle
{% endblock body_title %}

{% block content %}
    <ul>
        <li>Nombre: {{ object.nombre }}</li>
        <li>Descripción: {{ object.descripcion }}</li>
    </ul>
    <div>
        <a href="{% url 'producto:productocategoria_list' %}">Volver</a>
    </div>
{% endblock content %}

project/producto/templates/producto/productocategoria_form.html
{% extends 'core/base.html' %}

{% block title %}
    Producto | Categoría de Productos
{% endblock title %}

{% block body_title %}
    {% if form.instance.pk %}
        Producto - Categorías de Productos: Edición
    {% else %}
        Producto - Categorías de Productos: Creación
    {% endif %}
{% endblock body_title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Guardar</button>
    </form>
{% endblock content %}

project/producto/templates/producto/productocategoria_list.html
{% extends 'core/base.html' %}

{% block title %}
    Producto | Categoría de Productos
{% endblock title %}

{% block body_title %}
    Producto - Categorías de Productos: Listado
{% endblock body_title %}

{% block content %}
    <div class="container mt-5">
        <div class="row mb-3">
            <div class="col-lg-6">
                <form action="{% url 'producto:productocategoria_list' %}"
                      method="get"
                      class="input-group">
                    <input type="text"
                           name="busqueda"
                           class="form-control"
                           placeholder="Buscar...">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">Buscar</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>{{ object.nombre }}</td>
                            <td>
                                <a href="{% url 'producto:productocategoria_detail' object.id %}"
                                   class="btn btn-info btn-sm">Detalle</a>
                                <a href="{% url 'producto:productocategoria_update' object.id %}"
                                   class="btn btn-warning btn-sm">Cambiar</a>
                                <a href="{% url 'producto:productocategoria_delete' object.id %}"
                                   class="btn btn-danger btn-sm">Borrar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}